<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="simultan" nsURI="http://tuwien.ac.at/simultan" nsPrefix="simultan">
  <eClassifiers xsi:type="ecore:EClass" name="Simultan">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="globalId" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileVersion" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" ordered="false"
        upperBound="-1" eType="#//SimComponentSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simNetworks" ordered="false"
        upperBound="-1" eType="#//SimNetworkSerializable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimNetworkSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subnetworks" ordered="false"
        upperBound="-1" eType="#//SimNetworkSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" ordered="false"
        upperBound="-1" eType="#//SimNetworkBlocksSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" ordered="false"
        upperBound="-1" eType="#//SimNetworkPortSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" ordered="false"
        upperBound="-1" eType="#//SimNetworkConnectorSerializable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimNetworkBlocksSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" ordered="false"
        upperBound="-1" eType="#//SimNetworkPortSerializable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimNetworkPortSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portType" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimNetworkConnectorSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimBaseParameterSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAutomaticallyGenerated"
        ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" ordered="false" eType="#//SimTaxonomyEntryOrStringSerializable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimTaxonomyEntryOrStringSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taxonomyEntry" ordered="false"
        eType="#//SimTaxonomyEntryReferenceSerializable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimTaxonomyEntryReferenceSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxonomyKey" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxonomyEntryKey" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ISimInstancePlacementSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkId" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkElementId" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimInstanceSizeSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimInstanceSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceType" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceRotation" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InstanceParameters" ordered="false"
        upperBound="-1" transient="true">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placements" ordered="false"
        upperBound="-1" eType="#//ISimInstancePlacementSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instanceSize" ordered="false"
        eType="#//SimInstanceSizeSerializable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimSlotSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slotExtension" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" ordered="false" eType="#//SimTaxonomyEntryReferenceSerializable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimComponentSerializable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceType" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" ordered="false"
        upperBound="-1" eType="#//SimBaseParameterSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slots" ordered="false"
        upperBound="-1" eType="#//SimTaxonomyEntryReferenceSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" ordered="false"
        upperBound="-1" eType="#//SimInstanceSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" ordered="false"
        upperBound="-1" eType="#//SimChildComponentSerializable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimChildComponentSerializable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" ordered="false"
        eType="#//SimComponentSerializable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" ordered="false" eType="#//SimSlotSerializable"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
